name: Wave Application CI

on:
  workflow_call:
    inputs:
      application_name:
        description: Application name
        required: true
        type: string

      dockerfile:
        description: Path to Dockerfile
        required: false
        default: Dockerfile
        type: string

      build_context:
        description: Docker build context
        required: false
        default: .
        type: string

      registry_name:
        description: Azure Container Registry name
        required: true
        type: string

      registry_login_server:
        description: Azure Container Registry login server
        required: true
        type: string

      gitops_repository:
        description: GitOps repository in owner/repository format
        required: true
        type: string

      gitops_branch:
        description: GitOps branch
        required: false
        default: main
        type: string

      deployment_file:
        description: Kubernetes deployment manifest in GitOps repository
        required: true
        type: string

      environment:
        description: Target environment
        required: true
        type: string

    secrets:
      azure_client_id:
        required: true

      azure_tenant_id:
        required: true

      azure_subscription_id:
        required: true

      gitops_token:
        required: true

jobs:

  build:
    uses: ./.github/workflows/container-build.yml
    with:
      application_name: ${{ inputs.application_name }}
      dockerfile: ${{ inputs.dockerfile }}
      build_context: ${{ inputs.build_context }}
      image_tag: ${{ github.run_number }}

  publish:
    needs: build

    uses: ./.github/workflows/container-publish.yml

    permissions:
      contents: read
      id-token: write

    with:
      application_name: ${{ inputs.application_name }}
      image_tag: ${{ github.run_number }}
      registry_name: ${{ inputs.registry_name }}
      registry_login_server: ${{ inputs.registry_login_server }}

    secrets:
      azure_client_id: ${{ secrets.azure_client_id }}
      azure_tenant_id: ${{ secrets.azure_tenant_id }}
      azure_subscription_id: ${{ secrets.azure_subscription_id }}

  promote:
    needs: publish

    uses: ./.github/workflows/gitops-promotion.yml

    with:
      application_name: ${{ inputs.application_name }}
      image_tag: ${{ github.run_number }}
      registry_login_server: ${{ inputs.registry_login_server }}
      gitops_repository: ${{ inputs.gitops_repository }}
      gitops_branch: ${{ inputs.gitops_branch }}
      deployment_file: ${{ inputs.deployment_file }}
      environment: ${{ inputs.environment }}

    secrets:
      gitops_token: ${{ secrets.gitops_token }}